FROM nvidia/cuda:8.0-cudnn7-devel-ubuntu16.04
LABEL original from aidenlab/juicer, modified by Ryuichiro Nakato <rnakato@iqb.u-tokyo.ac.jp>

# For sorting, LC_ALL is C
ENV LC_ALL C
ENV PATH=/opt:/opt/juicer/scripts:/opt/juicer/scripts/common:/opt/script_Hi-C:/opt/conda/bin/:$PATH

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES all

RUN apt-get update \
     && apt-get install -y --no-install-recommends \
     bwa \
     bzip2 \
     curl \
     default-jdk \
     gawk \
     gcc \
     git \
     libbz2-dev \
     libz-dev \
     locales \
     make \
     pigz \
     qtcreator \
     r-base \
     samtools \
     wget \
     unzip \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/*

# Anaconda3 (2020.02)
RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh -O ~/anaconda.sh \
     && bash ~/anaconda.sh -b -p /opt/conda \
     && rm ~/anaconda.sh \
     && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

RUN pip install numpy pandas scipy matplotlib argparse seaborn \
    && conda install -y r-base \
    && conda install -c r r-ggplot2 r-reshape2

#RUN R -e "install.packages(c('ggplot2','reshape2','devtools'), repos='https://cran.ism.ac.jp/')"

# GAWK has the 'and' function, needed for chimeric_blacklist
RUN echo 'alias awk=gawk' >> ~/.bashrc

# Need to be sure we have this for stats
RUN locale-gen en_US.UTF-8

WORKDIR /opt/

# Install Juicer
ADD Juicebox.jar .
ADD juicer_1.5.7 juicer
ADD script_Hi-C script_Hi-C
ADD RPE_Hapmap RPE_Hapmap

# Install Juicer tools
ADD juicer_tools.1.9.9_jcuda.0.8.jar /opt/juicer/scripts/common/juicer_tools.jar
#ADD juicer_tools.2.13.07.jar /opt/juicer/scripts/common/juicer_tools.jar

COPY bedtools /usr/local/bin/bedtools
RUN chmod +x script_Hi-C/* /usr/local/bin/bedtools /opt/juicer/scripts/common/* /opt/juicer/scripts/*

# Error "Qt: Failed to create XKB context!"
# https://stackoverflow.com/questions/26974644/no-keyboard-input-in-qt-creator-after-update-to-qt5
ENV QT_XKB_CONFIG_ROOT /usr/share/X11/xkb
#RUN qtcreator
